endpoints:
  - name: facebook
    group: social-media
    url: "https://www.facebook.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 3000"

  - name: linkedin
    group: social-media
    url: "https://www.linkedin.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 3000"

  - name: instagram
    group: social-media
    url: "https://www.instagram.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 3000"

  - name: youtube
    group: social-media
    url: "https://www.youtube.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 3000"

  - name: tiktok
    group: social-media
    url: "https://www.tiktok.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 3000"

  - name: x
    group: social-media
    url: "https://www.x.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 3000"
